// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"learning-platform/internal/configs"
	"learning-platform/internal/handlers"
	"learning-platform/internal/platform/db"
	"learning-platform/internal/platform/jwt"
	"learning-platform/internal/repositories"
	"learning-platform/internal/services"
)

// Injectors from wire.go:

func Initialize() (*Container, error) {
	config, err := configs.LoadConfig()
	if err != nil {
		return nil, err
	}
	pool, err := db.ConnectDB(config)
	if err != nil {
		return nil, err
	}
	userRepository := repositories.NewUserRepository(pool)
	manager := jwt.Provide(config)
	authService := services.NewAuthService(userRepository, manager)
	userService := services.NewUserService(userRepository)
	authHandler := handlers.NewAuthHandler(authService, userService)
	userHandler := handlers.NewUserHandler(userService)
	container := &Container{
		AuthHandler: authHandler,
		JWTManager:  manager,
		UserHandler: userHandler,
	}
	return container, nil
}
