// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"learning-platform/internal/configs"
	"learning-platform/internal/handlers"
	"learning-platform/internal/platform/db"
	"learning-platform/internal/platform/jwt"
	"learning-platform/internal/repositories"
	"learning-platform/internal/services"
)

// Injectors from wire.go:

func Initialize() (*Container, error) {
	config, err := configs.LoadConfig()
	if err != nil {
		return nil, err
	}
	pool, err := db.ConnectDB(config)
	if err != nil {
		return nil, err
	}
	userRepository := repositories.NewUserRepository(pool)
	manager := jwt.Provide(config)
	authService := services.NewAuthService(userRepository, manager)
	userService := services.NewUserService(userRepository)
	authHandler := handlers.NewAuthHandler(authService, userService)
	userHandler := handlers.NewUserHandler(userService)
	courseRepository := repositories.NewCourseRepository(pool)
	courseService := services.NewCourseService(courseRepository)
	courseHandler := handlers.NewCourseHandler(courseService)
	lessonRepository := repositories.NewLessonRepository(pool)
	lessonService := services.NewLessonService(lessonRepository)
	lessonHandler := handlers.NewLessonHandler(lessonService)
	enrollmentRepository := repositories.NewEnrollmentRepository(pool)
	enrollmentService := services.NewEnrollmentService(enrollmentRepository, courseRepository)
	enrollmentHandler := handlers.NewEnrollmentHandler(enrollmentService)
	progressRepository := repositories.NewProgressRepository(pool)
	progressService := services.NewProgressService(progressRepository, enrollmentRepository)
	progressHandler := handlers.NewProgressHandler(progressService)
	container := &Container{
		AuthHandler:       authHandler,
		JWTManager:        manager,
		UserHandler:       userHandler,
		CourseHandler:     courseHandler,
		LessonHandler:     lessonHandler,
		EnrollmentHandler: enrollmentHandler,
		ProgressHandler:   progressHandler,
	}
	return container, nil
}
