// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"
	"learning-platform/internal/models"

	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockCache
func (_mock *MockCache) Delete(c context.Context, key string) error {
	ret := _mock.Called(c, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(c, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCache_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - c context.Context
//   - key string
func (_e *MockCache_Expecter) Delete(c any, key any) *MockCache_Delete_Call {
	return &MockCache_Delete_Call{Call: _e.mock.On("Delete", c, key)}
}

func (_c *MockCache_Delete_Call) Run(run func(c context.Context, key string)) *MockCache_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_Delete_Call) Return(err error) *MockCache_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_Delete_Call) RunAndReturn(run func(c context.Context, key string) error) *MockCache_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByPattern provides a mock function for the type MockCache
func (_mock *MockCache) DeleteByPattern(ctx context.Context, pattern string) error {
	ret := _mock.Called(ctx, pattern)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByPattern")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, pattern)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_DeleteByPattern_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByPattern'
type MockCache_DeleteByPattern_Call struct {
	*mock.Call
}

// DeleteByPattern is a helper method to define mock.On call
//   - ctx context.Context
//   - pattern string
func (_e *MockCache_Expecter) DeleteByPattern(ctx any, pattern any) *MockCache_DeleteByPattern_Call {
	return &MockCache_DeleteByPattern_Call{Call: _e.mock.On("DeleteByPattern", ctx, pattern)}
}

func (_c *MockCache_DeleteByPattern_Call) Run(run func(ctx context.Context, pattern string)) *MockCache_DeleteByPattern_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_DeleteByPattern_Call) Return(err error) *MockCache_DeleteByPattern_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_DeleteByPattern_Call) RunAndReturn(run func(ctx context.Context, pattern string) error) *MockCache_DeleteByPattern_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockCache
func (_mock *MockCache) Get(c context.Context, key string) (string, error) {
	ret := _mock.Called(c, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(c, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(c, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(c, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - c context.Context
//   - key string
func (_e *MockCache_Expecter) Get(c any, key any) *MockCache_Get_Call {
	return &MockCache_Get_Call{Call: _e.mock.On("Get", c, key)}
}

func (_c *MockCache_Get_Call) Run(run func(c context.Context, key string)) *MockCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_Get_Call) Return(s string, err error) *MockCache_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCache_Get_Call) RunAndReturn(run func(c context.Context, key string) (string, error)) *MockCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockCache
func (_mock *MockCache) Set(c context.Context, key string, value string) error {
	ret := _mock.Called(c, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(c, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - c context.Context
//   - key string
//   - value string
func (_e *MockCache_Expecter) Set(c any, key any, value any) *MockCache_Set_Call {
	return &MockCache_Set_Call{Call: _e.mock.On("Set", c, key, value)}
}

func (_c *MockCache_Set_Call) Run(run func(c context.Context, key string, value string)) *MockCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCache_Set_Call) Return(err error) *MockCache_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_Set_Call) RunAndReturn(run func(c context.Context, key string, value string) error) *MockCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCourseRepository creates a new instance of MockCourseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCourseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCourseRepository {
	mock := &MockCourseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCourseRepository is an autogenerated mock type for the CourseRepository type
type MockCourseRepository struct {
	mock.Mock
}

type MockCourseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCourseRepository) EXPECT() *MockCourseRepository_Expecter {
	return &MockCourseRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCourseRepository
func (_mock *MockCourseRepository) Create(c context.Context, course *models.Course) error {
	ret := _mock.Called(c, course)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Course) error); ok {
		r0 = returnFunc(c, course)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCourseRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCourseRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - c context.Context
//   - course *models.Course
func (_e *MockCourseRepository_Expecter) Create(c any, course any) *MockCourseRepository_Create_Call {
	return &MockCourseRepository_Create_Call{Call: _e.mock.On("Create", c, course)}
}

func (_c *MockCourseRepository_Create_Call) Run(run func(c context.Context, course *models.Course)) *MockCourseRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Course
		if args[1] != nil {
			arg1 = args[1].(*models.Course)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCourseRepository_Create_Call) Return(err error) *MockCourseRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCourseRepository_Create_Call) RunAndReturn(run func(c context.Context, course *models.Course) error) *MockCourseRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DecrementSeats provides a mock function for the type MockCourseRepository
func (_mock *MockCourseRepository) DecrementSeats(c context.Context, courseID int64) (bool, error) {
	ret := _mock.Called(c, courseID)

	if len(ret) == 0 {
		panic("no return value specified for DecrementSeats")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return returnFunc(c, courseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = returnFunc(c, courseID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(c, courseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCourseRepository_DecrementSeats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementSeats'
type MockCourseRepository_DecrementSeats_Call struct {
	*mock.Call
}

// DecrementSeats is a helper method to define mock.On call
//   - c context.Context
//   - courseID int64
func (_e *MockCourseRepository_Expecter) DecrementSeats(c any, courseID any) *MockCourseRepository_DecrementSeats_Call {
	return &MockCourseRepository_DecrementSeats_Call{Call: _e.mock.On("DecrementSeats", c, courseID)}
}

func (_c *MockCourseRepository_DecrementSeats_Call) Run(run func(c context.Context, courseID int64)) *MockCourseRepository_DecrementSeats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCourseRepository_DecrementSeats_Call) Return(b bool, err error) *MockCourseRepository_DecrementSeats_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockCourseRepository_DecrementSeats_Call) RunAndReturn(run func(c context.Context, courseID int64) (bool, error)) *MockCourseRepository_DecrementSeats_Call {
	_c.Call.Return(run)
	return _c
}

// DecrementSeatsTx provides a mock function for the type MockCourseRepository
func (_mock *MockCourseRepository) DecrementSeatsTx(c context.Context, tx pgx.Tx, courseID int64) (bool, error) {
	ret := _mock.Called(c, tx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for DecrementSeatsTx")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) (bool, error)); ok {
		return returnFunc(c, tx, courseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) bool); ok {
		r0 = returnFunc(c, tx, courseID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.Tx, int64) error); ok {
		r1 = returnFunc(c, tx, courseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCourseRepository_DecrementSeatsTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementSeatsTx'
type MockCourseRepository_DecrementSeatsTx_Call struct {
	*mock.Call
}

// DecrementSeatsTx is a helper method to define mock.On call
//   - c context.Context
//   - tx pgx.Tx
//   - courseID int64
func (_e *MockCourseRepository_Expecter) DecrementSeatsTx(c any, tx any, courseID any) *MockCourseRepository_DecrementSeatsTx_Call {
	return &MockCourseRepository_DecrementSeatsTx_Call{Call: _e.mock.On("DecrementSeatsTx", c, tx, courseID)}
}

func (_c *MockCourseRepository_DecrementSeatsTx_Call) Run(run func(c context.Context, tx pgx.Tx, courseID int64)) *MockCourseRepository_DecrementSeatsTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCourseRepository_DecrementSeatsTx_Call) Return(b bool, err error) *MockCourseRepository_DecrementSeatsTx_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockCourseRepository_DecrementSeatsTx_Call) RunAndReturn(run func(c context.Context, tx pgx.Tx, courseID int64) (bool, error)) *MockCourseRepository_DecrementSeatsTx_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCourseRepository
func (_mock *MockCourseRepository) Delete(c context.Context, id int64) error {
	ret := _mock.Called(c, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(c, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCourseRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCourseRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - c context.Context
//   - id int64
func (_e *MockCourseRepository_Expecter) Delete(c any, id any) *MockCourseRepository_Delete_Call {
	return &MockCourseRepository_Delete_Call{Call: _e.mock.On("Delete", c, id)}
}

func (_c *MockCourseRepository_Delete_Call) Run(run func(c context.Context, id int64)) *MockCourseRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCourseRepository_Delete_Call) Return(err error) *MockCourseRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCourseRepository_Delete_Call) RunAndReturn(run func(c context.Context, id int64) error) *MockCourseRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockCourseRepository
func (_mock *MockCourseRepository) GetByID(c context.Context, id int64) (*models.Course, error) {
	ret := _mock.Called(c, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Course
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*models.Course, error)); ok {
		return returnFunc(c, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *models.Course); ok {
		r0 = returnFunc(c, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Course)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(c, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCourseRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCourseRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - c context.Context
//   - id int64
func (_e *MockCourseRepository_Expecter) GetByID(c any, id any) *MockCourseRepository_GetByID_Call {
	return &MockCourseRepository_GetByID_Call{Call: _e.mock.On("GetByID", c, id)}
}

func (_c *MockCourseRepository_GetByID_Call) Run(run func(c context.Context, id int64)) *MockCourseRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCourseRepository_GetByID_Call) Return(course *models.Course, err error) *MockCourseRepository_GetByID_Call {
	_c.Call.Return(course, err)
	return _c
}

func (_c *MockCourseRepository_GetByID_Call) RunAndReturn(run func(c context.Context, id int64) (*models.Course, error)) *MockCourseRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeatsByIDs provides a mock function for the type MockCourseRepository
func (_mock *MockCourseRepository) GetSeatsByIDs(c context.Context, courseIDs []int64) (map[int64]int, error) {
	ret := _mock.Called(c, courseIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetSeatsByIDs")
	}

	var r0 map[int64]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) (map[int64]int, error)); ok {
		return returnFunc(c, courseIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64) map[int64]int); ok {
		r0 = returnFunc(c, courseIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = returnFunc(c, courseIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCourseRepository_GetSeatsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeatsByIDs'
type MockCourseRepository_GetSeatsByIDs_Call struct {
	*mock.Call
}

// GetSeatsByIDs is a helper method to define mock.On call
//   - c context.Context
//   - courseIDs []int64
func (_e *MockCourseRepository_Expecter) GetSeatsByIDs(c any, courseIDs any) *MockCourseRepository_GetSeatsByIDs_Call {
	return &MockCourseRepository_GetSeatsByIDs_Call{Call: _e.mock.On("GetSeatsByIDs", c, courseIDs)}
}

func (_c *MockCourseRepository_GetSeatsByIDs_Call) Run(run func(c context.Context, courseIDs []int64)) *MockCourseRepository_GetSeatsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		if args[1] != nil {
			arg1 = args[1].([]int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCourseRepository_GetSeatsByIDs_Call) Return(int64ToInt map[int64]int, err error) *MockCourseRepository_GetSeatsByIDs_Call {
	_c.Call.Return(int64ToInt, err)
	return _c
}

func (_c *MockCourseRepository_GetSeatsByIDs_Call) RunAndReturn(run func(c context.Context, courseIDs []int64) (map[int64]int, error)) *MockCourseRepository_GetSeatsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementSeatsTx provides a mock function for the type MockCourseRepository
func (_mock *MockCourseRepository) IncrementSeatsTx(c context.Context, tx pgx.Tx, courseID int64) (bool, error) {
	ret := _mock.Called(c, tx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for IncrementSeatsTx")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) (bool, error)); ok {
		return returnFunc(c, tx, courseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) bool); ok {
		r0 = returnFunc(c, tx, courseID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.Tx, int64) error); ok {
		r1 = returnFunc(c, tx, courseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCourseRepository_IncrementSeatsTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementSeatsTx'
type MockCourseRepository_IncrementSeatsTx_Call struct {
	*mock.Call
}

// IncrementSeatsTx is a helper method to define mock.On call
//   - c context.Context
//   - tx pgx.Tx
//   - courseID int64
func (_e *MockCourseRepository_Expecter) IncrementSeatsTx(c any, tx any, courseID any) *MockCourseRepository_IncrementSeatsTx_Call {
	return &MockCourseRepository_IncrementSeatsTx_Call{Call: _e.mock.On("IncrementSeatsTx", c, tx, courseID)}
}

func (_c *MockCourseRepository_IncrementSeatsTx_Call) Run(run func(c context.Context, tx pgx.Tx, courseID int64)) *MockCourseRepository_IncrementSeatsTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCourseRepository_IncrementSeatsTx_Call) Return(b bool, err error) *MockCourseRepository_IncrementSeatsTx_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockCourseRepository_IncrementSeatsTx_Call) RunAndReturn(run func(c context.Context, tx pgx.Tx, courseID int64) (bool, error)) *MockCourseRepository_IncrementSeatsTx_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockCourseRepository
func (_mock *MockCourseRepository) List(c context.Context, filter *CourseFilter) ([]*models.Course, error) {
	ret := _mock.Called(c, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Course
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CourseFilter) ([]*models.Course, error)); ok {
		return returnFunc(c, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *CourseFilter) []*models.Course); ok {
		r0 = returnFunc(c, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Course)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *CourseFilter) error); ok {
		r1 = returnFunc(c, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCourseRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCourseRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - c context.Context
//   - filter *CourseFilter
func (_e *MockCourseRepository_Expecter) List(c any, filter any) *MockCourseRepository_List_Call {
	return &MockCourseRepository_List_Call{Call: _e.mock.On("List", c, filter)}
}

func (_c *MockCourseRepository_List_Call) Run(run func(c context.Context, filter *CourseFilter)) *MockCourseRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *CourseFilter
		if args[1] != nil {
			arg1 = args[1].(*CourseFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCourseRepository_List_Call) Return(courses []*models.Course, err error) *MockCourseRepository_List_Call {
	_c.Call.Return(courses, err)
	return _c
}

func (_c *MockCourseRepository_List_Call) RunAndReturn(run func(c context.Context, filter *CourseFilter) ([]*models.Course, error)) *MockCourseRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockCourseRepository
func (_mock *MockCourseRepository) Update(c context.Context, course *models.Course) error {
	ret := _mock.Called(c, course)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Course) error); ok {
		r0 = returnFunc(c, course)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCourseRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCourseRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - c context.Context
//   - course *models.Course
func (_e *MockCourseRepository_Expecter) Update(c any, course any) *MockCourseRepository_Update_Call {
	return &MockCourseRepository_Update_Call{Call: _e.mock.On("Update", c, course)}
}

func (_c *MockCourseRepository_Update_Call) Run(run func(c context.Context, course *models.Course)) *MockCourseRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Course
		if args[1] != nil {
			arg1 = args[1].(*models.Course)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCourseRepository_Update_Call) Return(err error) *MockCourseRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCourseRepository_Update_Call) RunAndReturn(run func(c context.Context, course *models.Course) error) *MockCourseRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEnrollmentRepository creates a new instance of MockEnrollmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnrollmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnrollmentRepository {
	mock := &MockEnrollmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEnrollmentRepository is an autogenerated mock type for the EnrollmentRepository type
type MockEnrollmentRepository struct {
	mock.Mock
}

type MockEnrollmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnrollmentRepository) EXPECT() *MockEnrollmentRepository_Expecter {
	return &MockEnrollmentRepository_Expecter{mock: &_m.Mock}
}

// CountByCourseID provides a mock function for the type MockEnrollmentRepository
func (_mock *MockEnrollmentRepository) CountByCourseID(c context.Context, courseID int64) (int64, error) {
	ret := _mock.Called(c, courseID)

	if len(ret) == 0 {
		panic("no return value specified for CountByCourseID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return returnFunc(c, courseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = returnFunc(c, courseID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(c, courseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEnrollmentRepository_CountByCourseID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByCourseID'
type MockEnrollmentRepository_CountByCourseID_Call struct {
	*mock.Call
}

// CountByCourseID is a helper method to define mock.On call
//   - c context.Context
//   - courseID int64
func (_e *MockEnrollmentRepository_Expecter) CountByCourseID(c any, courseID any) *MockEnrollmentRepository_CountByCourseID_Call {
	return &MockEnrollmentRepository_CountByCourseID_Call{Call: _e.mock.On("CountByCourseID", c, courseID)}
}

func (_c *MockEnrollmentRepository_CountByCourseID_Call) Run(run func(c context.Context, courseID int64)) *MockEnrollmentRepository_CountByCourseID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEnrollmentRepository_CountByCourseID_Call) Return(n int64, err error) *MockEnrollmentRepository_CountByCourseID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockEnrollmentRepository_CountByCourseID_Call) RunAndReturn(run func(c context.Context, courseID int64) (int64, error)) *MockEnrollmentRepository_CountByCourseID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockEnrollmentRepository
func (_mock *MockEnrollmentRepository) Create(c context.Context, enrollment *models.Enrollment) (*models.Enrollment, error) {
	ret := _mock.Called(c, enrollment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Enrollment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Enrollment) (*models.Enrollment, error)); ok {
		return returnFunc(c, enrollment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Enrollment) *models.Enrollment); ok {
		r0 = returnFunc(c, enrollment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Enrollment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.Enrollment) error); ok {
		r1 = returnFunc(c, enrollment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEnrollmentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEnrollmentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - c context.Context
//   - enrollment *models.Enrollment
func (_e *MockEnrollmentRepository_Expecter) Create(c any, enrollment any) *MockEnrollmentRepository_Create_Call {
	return &MockEnrollmentRepository_Create_Call{Call: _e.mock.On("Create", c, enrollment)}
}

func (_c *MockEnrollmentRepository_Create_Call) Run(run func(c context.Context, enrollment *models.Enrollment)) *MockEnrollmentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Enrollment
		if args[1] != nil {
			arg1 = args[1].(*models.Enrollment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEnrollmentRepository_Create_Call) Return(enrollment1 *models.Enrollment, err error) *MockEnrollmentRepository_Create_Call {
	_c.Call.Return(enrollment1, err)
	return _c
}

func (_c *MockEnrollmentRepository_Create_Call) RunAndReturn(run func(c context.Context, enrollment *models.Enrollment) (*models.Enrollment, error)) *MockEnrollmentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTx provides a mock function for the type MockEnrollmentRepository
func (_mock *MockEnrollmentRepository) CreateTx(c context.Context, tx pgx.Tx, enrollment *models.Enrollment) (*models.Enrollment, error) {
	ret := _mock.Called(c, tx, enrollment)

	if len(ret) == 0 {
		panic("no return value specified for CreateTx")
	}

	var r0 *models.Enrollment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, *models.Enrollment) (*models.Enrollment, error)); ok {
		return returnFunc(c, tx, enrollment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, *models.Enrollment) *models.Enrollment); ok {
		r0 = returnFunc(c, tx, enrollment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Enrollment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.Tx, *models.Enrollment) error); ok {
		r1 = returnFunc(c, tx, enrollment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEnrollmentRepository_CreateTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTx'
type MockEnrollmentRepository_CreateTx_Call struct {
	*mock.Call
}

// CreateTx is a helper method to define mock.On call
//   - c context.Context
//   - tx pgx.Tx
//   - enrollment *models.Enrollment
func (_e *MockEnrollmentRepository_Expecter) CreateTx(c any, tx any, enrollment any) *MockEnrollmentRepository_CreateTx_Call {
	return &MockEnrollmentRepository_CreateTx_Call{Call: _e.mock.On("CreateTx", c, tx, enrollment)}
}

func (_c *MockEnrollmentRepository_CreateTx_Call) Run(run func(c context.Context, tx pgx.Tx, enrollment *models.Enrollment)) *MockEnrollmentRepository_CreateTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 *models.Enrollment
		if args[2] != nil {
			arg2 = args[2].(*models.Enrollment)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEnrollmentRepository_CreateTx_Call) Return(enrollment1 *models.Enrollment, err error) *MockEnrollmentRepository_CreateTx_Call {
	_c.Call.Return(enrollment1, err)
	return _c
}

func (_c *MockEnrollmentRepository_CreateTx_Call) RunAndReturn(run func(c context.Context, tx pgx.Tx, enrollment *models.Enrollment) (*models.Enrollment, error)) *MockEnrollmentRepository_CreateTx_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockEnrollmentRepository
func (_mock *MockEnrollmentRepository) Delete(c context.Context, id int64) error {
	ret := _mock.Called(c, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(c, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEnrollmentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockEnrollmentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - c context.Context
//   - id int64
func (_e *MockEnrollmentRepository_Expecter) Delete(c any, id any) *MockEnrollmentRepository_Delete_Call {
	return &MockEnrollmentRepository_Delete_Call{Call: _e.mock.On("Delete", c, id)}
}

func (_c *MockEnrollmentRepository_Delete_Call) Run(run func(c context.Context, id int64)) *MockEnrollmentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEnrollmentRepository_Delete_Call) Return(err error) *MockEnrollmentRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEnrollmentRepository_Delete_Call) RunAndReturn(run func(c context.Context, id int64) error) *MockEnrollmentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTx provides a mock function for the type MockEnrollmentRepository
func (_mock *MockEnrollmentRepository) DeleteTx(c context.Context, tx pgx.Tx, id int64) error {
	ret := _mock.Called(c, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) error); ok {
		r0 = returnFunc(c, tx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEnrollmentRepository_DeleteTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTx'
type MockEnrollmentRepository_DeleteTx_Call struct {
	*mock.Call
}

// DeleteTx is a helper method to define mock.On call
//   - c context.Context
//   - tx pgx.Tx
//   - id int64
func (_e *MockEnrollmentRepository_Expecter) DeleteTx(c any, tx any, id any) *MockEnrollmentRepository_DeleteTx_Call {
	return &MockEnrollmentRepository_DeleteTx_Call{Call: _e.mock.On("DeleteTx", c, tx, id)}
}

func (_c *MockEnrollmentRepository_DeleteTx_Call) Run(run func(c context.Context, tx pgx.Tx, id int64)) *MockEnrollmentRepository_DeleteTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEnrollmentRepository_DeleteTx_Call) Return(err error) *MockEnrollmentRepository_DeleteTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEnrollmentRepository_DeleteTx_Call) RunAndReturn(run func(c context.Context, tx pgx.Tx, id int64) error) *MockEnrollmentRepository_DeleteTx_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockEnrollmentRepository
func (_mock *MockEnrollmentRepository) FindByID(c context.Context, id int64) (*models.Enrollment, error) {
	ret := _mock.Called(c, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Enrollment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*models.Enrollment, error)); ok {
		return returnFunc(c, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *models.Enrollment); ok {
		r0 = returnFunc(c, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Enrollment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(c, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEnrollmentRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockEnrollmentRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - c context.Context
//   - id int64
func (_e *MockEnrollmentRepository_Expecter) FindByID(c any, id any) *MockEnrollmentRepository_FindByID_Call {
	return &MockEnrollmentRepository_FindByID_Call{Call: _e.mock.On("FindByID", c, id)}
}

func (_c *MockEnrollmentRepository_FindByID_Call) Run(run func(c context.Context, id int64)) *MockEnrollmentRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEnrollmentRepository_FindByID_Call) Return(enrollment *models.Enrollment, err error) *MockEnrollmentRepository_FindByID_Call {
	_c.Call.Return(enrollment, err)
	return _c
}

func (_c *MockEnrollmentRepository_FindByID_Call) RunAndReturn(run func(c context.Context, id int64) (*models.Enrollment, error)) *MockEnrollmentRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserIDAndCourseID provides a mock function for the type MockEnrollmentRepository
func (_mock *MockEnrollmentRepository) FindByUserIDAndCourseID(c context.Context, userID int64, courseID int64) (*models.Enrollment, error) {
	ret := _mock.Called(c, userID, courseID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserIDAndCourseID")
	}

	var r0 *models.Enrollment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*models.Enrollment, error)); ok {
		return returnFunc(c, userID, courseID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *models.Enrollment); ok {
		r0 = returnFunc(c, userID, courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Enrollment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(c, userID, courseID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEnrollmentRepository_FindByUserIDAndCourseID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserIDAndCourseID'
type MockEnrollmentRepository_FindByUserIDAndCourseID_Call struct {
	*mock.Call
}

// FindByUserIDAndCourseID is a helper method to define mock.On call
//   - c context.Context
//   - userID int64
//   - courseID int64
func (_e *MockEnrollmentRepository_Expecter) FindByUserIDAndCourseID(c any, userID any, courseID any) *MockEnrollmentRepository_FindByUserIDAndCourseID_Call {
	return &MockEnrollmentRepository_FindByUserIDAndCourseID_Call{Call: _e.mock.On("FindByUserIDAndCourseID", c, userID, courseID)}
}

func (_c *MockEnrollmentRepository_FindByUserIDAndCourseID_Call) Run(run func(c context.Context, userID int64, courseID int64)) *MockEnrollmentRepository_FindByUserIDAndCourseID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEnrollmentRepository_FindByUserIDAndCourseID_Call) Return(enrollment *models.Enrollment, err error) *MockEnrollmentRepository_FindByUserIDAndCourseID_Call {
	_c.Call.Return(enrollment, err)
	return _c
}

func (_c *MockEnrollmentRepository_FindByUserIDAndCourseID_Call) RunAndReturn(run func(c context.Context, userID int64, courseID int64) (*models.Enrollment, error)) *MockEnrollmentRepository_FindByUserIDAndCourseID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockEnrollmentRepository
func (_mock *MockEnrollmentRepository) List(c context.Context, filter *EnrollmentFilter) ([]*models.Enrollment, error) {
	ret := _mock.Called(c, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Enrollment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *EnrollmentFilter) ([]*models.Enrollment, error)); ok {
		return returnFunc(c, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *EnrollmentFilter) []*models.Enrollment); ok {
		r0 = returnFunc(c, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Enrollment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *EnrollmentFilter) error); ok {
		r1 = returnFunc(c, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEnrollmentRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockEnrollmentRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - c context.Context
//   - filter *EnrollmentFilter
func (_e *MockEnrollmentRepository_Expecter) List(c any, filter any) *MockEnrollmentRepository_List_Call {
	return &MockEnrollmentRepository_List_Call{Call: _e.mock.On("List", c, filter)}
}

func (_c *MockEnrollmentRepository_List_Call) Run(run func(c context.Context, filter *EnrollmentFilter)) *MockEnrollmentRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *EnrollmentFilter
		if args[1] != nil {
			arg1 = args[1].(*EnrollmentFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEnrollmentRepository_List_Call) Return(enrollments []*models.Enrollment, err error) *MockEnrollmentRepository_List_Call {
	_c.Call.Return(enrollments, err)
	return _c
}

func (_c *MockEnrollmentRepository_List_Call) RunAndReturn(run func(c context.Context, filter *EnrollmentFilter) ([]*models.Enrollment, error)) *MockEnrollmentRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTxManager creates a new instance of MockTxManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxManager {
	mock := &MockTxManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxManager is an autogenerated mock type for the TxManager type
type MockTxManager struct {
	mock.Mock
}

type MockTxManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxManager) EXPECT() *MockTxManager_Expecter {
	return &MockTxManager_Expecter{mock: &_m.Mock}
}

// ExecTx provides a mock function for the type MockTxManager
func (_mock *MockTxManager) ExecTx(ctx context.Context, fn func(ctx context.Context, tx pgx.Tx) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for ExecTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context, tx pgx.Tx) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTxManager_ExecTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecTx'
type MockTxManager_ExecTx_Call struct {
	*mock.Call
}

// ExecTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context, tx pgx.Tx) error
func (_e *MockTxManager_Expecter) ExecTx(ctx any, fn any) *MockTxManager_ExecTx_Call {
	return &MockTxManager_ExecTx_Call{Call: _e.mock.On("ExecTx", ctx, fn)}
}

func (_c *MockTxManager_ExecTx_Call) Run(run func(ctx context.Context, fn func(ctx context.Context, tx pgx.Tx) error)) *MockTxManager_ExecTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context, tx pgx.Tx) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context, tx pgx.Tx) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxManager_ExecTx_Call) Return(err error) *MockTxManager_ExecTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTxManager_ExecTx_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context, tx pgx.Tx) error) error) *MockTxManager_ExecTx_Call {
	_c.Call.Return(run)
	return _c
}
